# Generated by Django 4.2.2 on 2023-07-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_spainsellersitem_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestosfuentesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=256, unique=True)),
                ('link', models.CharField(max_length=512)),
                ('item_name', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=256)),
                ('in_stock', models.BooleanField()),
            ],
            options={
                'verbose_name': 'RepuestosfuentesItem',
                'verbose_name_plural': 'RepuestosfuentesItems',
            },
        ),
        migrations.CreateModel(
            name='RepuestosfuentesLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'RepuestosfuentesLink',
                'verbose_name_plural': 'RepuestosfuentesLinks',
            },
        ),
    ]
