# Generated by Django 4.2.2 on 2023-07-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0006_lcphonesitem_lcphoneslinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvisatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=256, unique=True)),
                ('link', models.CharField(max_length=512)),
                ('item_name', models.CharField(max_length=512)),
                ('price', models.CharField(max_length=256)),
                ('in_stock', models.BooleanField()),
            ],
            options={
                'verbose_name': 'OvisatItem',
                'verbose_name_plural': 'OvisatItems',
            },
        ),
        migrations.CreateModel(
            name='OvisatLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OvisatLink',
                'verbose_name_plural': 'OvisatLinks',
            },
        ),
    ]
