# Generated by Django 4.2.2 on 2023-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0007_ovisatitem_ovisatlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chipspainitem',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='lcphonesitem',
            name='in_stock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lcphonesitem',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ovisatitem',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='preciosadictositem',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='repuestosfuentesitem',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='spainsellersitem',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
