# Generated by Django 4.2.2 on 2023-08-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0008_alter_chipspainitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourPhonesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=256, unique=True)),
                ('link', models.CharField(max_length=512)),
                ('item_name', models.CharField(max_length=512)),
                ('price', models.CharField(blank=True, max_length=256, null=True)),
                ('in_stock', models.BooleanField()),
            ],
            options={
                'verbose_name': 'FourPhonesItem',
                'verbose_name_plural': 'FourPhonesItems',
            },
        ),
        migrations.CreateModel(
            name='FourPhonesLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'FourPhonesLink',
                'verbose_name_plural': 'FourPhonesLinks',
            },
        ),
    ]
