# Generated by Django 4.2.2 on 2023-08-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0009_fourphonesitem_fourphoneslinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpainSellersLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=512, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SpainSellersLink',
                'verbose_name_plural': 'SpainSellersLinks',
            },
        ),
    ]
